import CarInspectionPlatformDashboard from './carinspectionplatform/CarInspectionPlatform.dashboard'
import VehicleServiceCompanyEmployeeCreateForm from './vehicleservicecompanyemployee/VehicleServiceCompanyEmployee.createform'

const result = {CarInspectionPlatformDashboard,VehicleServiceCompanyEmployeeCreateForm};

export default result;